import { expect, test } from '@playwright/test'

test('palace light changes the rendered scene and leaves the GPU idle after interaction', async ({ page, browserName, isMobile }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('console', message => { if (message.type() === 'error' && /THREE|WebGL|shader/i.test(message.text())) errors.push(message.text()) })
  await page.goto('/')
  await page.getByRole('button', { name: 'Explore in 3D' }).click()
  await expect(page.locator('.tour-canvas canvas, .tour-fallback')).toBeVisible({ timeout: 15000 })
  const canvas = page.locator('.tour-canvas canvas')
  if (browserName === 'chromium') await expect(canvas).toBeVisible()
  if (await canvas.count()) {
    await expect(page.getByRole('status')).toHaveCount(0, { timeout: 15000 })
    expect(Number(await canvas.getAttribute('data-triangles'))).toBeLessThan(100000)
    await test.info().attach('Palace render budget', { body: JSON.stringify({ triangles: Number(await canvas.getAttribute('data-triangles')), drawCalls: Number(await canvas.getAttribute('data-draw-calls')) }), contentType: 'application/json' })
    await expect(canvas).toHaveAttribute('data-lighting', 'night')
    await expect.poll(() => canvas.getAttribute('data-renders').then(Number)).toBeGreaterThan(0)
    const night = await canvas.screenshot({ scale: 'css' })
    await page.getByRole('button', { name: 'Daylight', exact: true }).click()
    await expect(canvas).toHaveAttribute('data-lighting', 'day')
    const daylight = await canvas.screenshot({ scale: 'css' })
    expect(Buffer.compare(night, daylight)).not.toBe(0)
    await page.evaluate(() => window.scrollTo({ top: document.querySelector('.tour-viewer')!.getBoundingClientRect().top + scrollY - 104, behavior: 'instant' }))
    await page.locator('.tour-viewer').screenshot({ path: `test-results/palace-daylight-${test.info().project.name}.png` })
    await page.getByRole('button', { name: 'Blue hour', exact: true }).click()
    await expect(canvas).toHaveAttribute('data-lighting', 'night')
    await expect(page.getByRole('button', { name: 'Blue hour', exact: true })).toHaveAttribute('aria-pressed', 'true')
    await page.waitForTimeout(350)
    const idleRenders = Number(await canvas.getAttribute('data-renders'))
    await page.waitForTimeout(450)
    expect(Number(await canvas.getAttribute('data-renders'))).toBe(idleRenders)
    await canvas.focus()
    await page.keyboard.press('ArrowRight')
    await expect.poll(() => canvas.getAttribute('data-renders').then(Number)).toBeGreaterThan(idleRenders)
    expect(Buffer.compare(night, await canvas.screenshot({ scale: 'css' }))).not.toBe(0)
    if (isMobile) {
      await page.getByRole('button', { name: 'Menu', exact: true }).click()
      await page.getByRole('navigation', { name: 'Mobile navigation' }).getByRole('button', { name: /Architecture/ }).click()
    } else await page.getByRole('navigation', { name: 'Primary navigation' }).getByRole('button', { name: 'Architecture', exact: true }).click()
    await expect(canvas).not.toBeInViewport()
    await page.waitForTimeout(300)
    const hiddenRenders = Number(await canvas.getAttribute('data-renders'))
    await page.waitForTimeout(450)
    expect(Number(await canvas.getAttribute('data-renders'))).toBe(hiddenRenders)
  }
  expect(errors).toEqual([])
})

test('a failed 3D download preserves the palace photograph and the rest of the website', async ({ page }) => {
  await page.route(/\/TourScene-.*\.js/, route => route.abort())
  await page.goto('/')
  await page.getByRole('button', { name: 'Explore in 3D' }).click()
  await expect(page.locator('.tour-fallback')).toBeVisible({ timeout: 15000 })
  await expect(page.locator('.tour-fallback img')).toHaveJSProperty('complete', true)
  await expect(page.getByRole('heading', { name: 'Where time moves differently.' })).toBeAttached()
  await page.getByRole('button', { name: 'Explore The Courtyard', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'The Courtyard' })).toBeVisible()
  await page.getByRole('button', { name: 'Close gallery', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'The Courtyard' })).toHaveCount(0)
})

test('palace reduced-motion visitors can change viewpoints and light without camera flights', async ({ page, browserName }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  await page.getByRole('button', { name: 'Explore in 3D' }).click()
  await expect(page.locator('.tour-canvas canvas, .tour-fallback')).toBeVisible({ timeout: 15000 })
  const canvas = page.locator('.tour-canvas canvas')
  if (browserName === 'chromium') await expect(canvas).toBeVisible()
  if (await canvas.count()) {
    await page.getByRole('button', { name: 'Grand salon', exact: true }).click()
    await expect(canvas).toHaveAttribute('data-state', 'ready')
    await expect(canvas).toHaveAttribute('data-view', 'Grand salon')
    await page.getByRole('button', { name: 'Daylight', exact: true }).click()
    await expect(canvas).toHaveAttribute('data-lighting', 'day')
    await expect(canvas).toHaveCSS('touch-action', 'pan-y')
  }
})
